# Generated by Django 4.2.4 on 2023-08-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_classroom_submission_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file_url',
            new_name='file',
        ),
    ]
