# Generated by Django 4.2.4 on 2023-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_file_url_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
