# Generated by Django 4.2.4 on 2023-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
